# This is a python script to test that all the subsets testing work

# imports
import os

# define the os_sep
if "/" in os.getcwd(): os_sep = "/"
elif "\\" in os.getcwd(): os_sep = "\\"
else: raise ValueError("unknown OS. This script is %s"%__file__)

# define the current directory
CurDir = os_sep.join(os.path.realpath(__file__).split(os_sep)[0:-1])

# test each of the samples that should work
for d in ["AST_48h_subset", "Classic_spottest_subset", "Fitness_only_subset", "Stress_plates_subset"]:

	# define the testdir
	test_dir = "%s/%s"%(CurDir, d)



# test that the errors generated by different plate layouts from Stress_plates_subset are meaningful



#output
#testing/testing_subsets/Stress_plates_subset/testing_different_platelayouts 