# FROM continuumio/miniconda3:4.10.3-alpine

# define the working directory (creates the folder /workdir_app inside the virtual machine)
WORKDIR /workdir_app

# create the base env
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-e", "-c"] # run from base env (it has 3.7.3 installed)

# create the colonyzer env
RUN conda create --name colonyzer_env python=2.7.15 numpy=1.16.5
SHELL ["conda", "run", "-n", "colonyzer_env", "/bin/bash", "-e", "-c"] # run from colonyzer_env
RUN pip install Colonyzer2==1.1.22 pygame==1.9.6 numpy==1.16.5

# give permissions
RUN chmod -R 755 /workdir_app

#### COMMENTS ####

# Create this image with 'docker build -t mikischikora/qcast_coords:v0.1 -f ./Dockerfile_coords .'
# Upload to dockerhub with 'docker push mikischikora/qcast_coords:v0.1'
# download with 'docker pull mikischikora/qcast_coords:v0.1'

# test in linux with:
# xhost +local:docker && docker run --rm -it  -v $PWD/testing/testing_subset/subset_raw_images/sc1_ANI/:/workdir_app/images -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix mikischikora/qcast_coords:v0.1 bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate colonyzer_env && cd images && parametryzer'

# test in Miki's mac with:
# xhost +192.168.1.128 && docker run --rm -it -v $PWD/testing/testing_subset/subset_raw_images/sc1_ANI/:/workdir_app/images -e DISPLAY=192.168.1.128:0 mikischikora/qcast_coords:v0.1 bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate colonyzer_env && cd images && parametryzer'

# old commands


##################